dist: trusty
sudo: required
group: beta
language: node_js
node_js:
  - "8"
cache:
  directories:
    - node_modules
before_install: npm install -g mocha
install: npm install
script:
  - npm i -g truffle
  - sh deploy.sh
  - npm run build
  - npm test
git:
  submodules: true
